In [6]:
%autosave 60

Autosaving every 60 seconds

In [7]:
BUCKET_NAME = "msil_raw"
FOLDER_NAME = "training_data"
TRAINFILE = "trainset.csv"
VALIDFILE = "validset.csv"
TESTFILE = "testset.csv"

In [8]:
import google.datalab.storage as storage
import pandas as pd
from io import BytesIO

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
from sklearn.model_selection import GridSearchCV
import time
from datetime import datetime
from scipy import integrate

In [4]:
# setting up the parameters
plt.rcParams["figure.figsize"] = (10, 10)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)
pd.set_option("precision", 15)
sns.set_style("darkgrid")

In [5]:
mybucket = storage.Bucket(BUCKET_NAME)
data_csv = mybucket.object(FOLDER_NAME + "/" + TESTFILE)

uri = data_csv.uri
%gcs read --object $uri --variable data

testset = pd.read_csv(BytesIO(data))
testset.head()

,IMEI,Year,Month,Day,Hour,Minute,Seconds,tp,sp,EVVSP,EVVSP_delta,EVVSP_change,EVGPO,EVOAS,EVIGM_Latest,EVCOM_Latest,EVACO_Z,EVIRT_Min,EVDI2,EVBMI_Latest,EVBMA_Latest,EVVAC,EVVAC_delta,EVVAC_change,EVODO,EVODOH,EVSMA_EWMA,EVSMA_delta,EVSMA_in,combine
0,7,2018,11,15,10,58,49,1,0.0,0.0,0.0,0.0,0,26.0,-51,-51,-1008.0,-41,20,21.5,21.5,0.0,0.0,0.0,690,0.0,93.200000000000003,0.0,93.200000000000003,1606
1,7,2018,11,15,10,58,50,1,1000.0,0.0,0.0,0.0,0,26.0,-51,-51,-1004.0,-41,20,21.5,21.5,0.0,0.0,0.0,690,0.0,93.200000000000003,0.0,93.200000000000003,1606
2,7,2018,11,15,10,58,51,1,2000.0,0.0,0.0,0.0,0,26.0,-51,-51,-1016.0,-41,20,21.5,21.5,0.0,0.0,0.0,690,0.0,93.200000000000003,0.0,93.200000000000003,1606
3,7,2018,11,15,10,58,52,1,3000.0,0.0,0.0,0.0,0,26.0,-51,-51,-1002.0,-41,20,21.5,21.5,0.0,0.0,0.0,690,0.0,93.200000000000003,0.0,93.200000000000003,1606
4,7,2018,11,15,10,58,53,1,4000.0,0.0,0.0,0.0,0,26.0,-51,-51,-1012.0,-41,20,21.5,21.5,0.0,0.0,0.0,690,0.0,93.200000000000003,0.0,93.200000000000003,1606

In [ ]:
import data_proces